### ISSUE TITLE
How to use the program to represent negation?

### ISSUE THREAD

**Issue by 14H034160212** [MNoorFawi/pytholog#4]
Hi,

Great project! I have several questions. 
1. How to use the program to represent negation?
2. Do you use any symbolic reasoner for your project? I have seen you are using backtracking. Is there any other algorithm like DPLL? Many thanks.

**Comment by 14H034160212** [comment]
I found negation is just add `-` before the predicate. It works.

**Comment by MNoorFawi** [comment]
Thanks for your feedback.
1. For negation you can use the `neq` keyword. For example, `neq(X, Y)` means X is not Y.
2. at the moment, the library only uses backtracking where not all the facts and rules are searched but only the relevant ones to improve speed. However, it is planned to add more advanced algorithms and functionalities, like lists, in the future but it is difficult at the moment as it is only one person working on the project.
